// chatbot-ui/src/app/features/chat-interface/components/chat-message/chat-message.component.ts
import { Component, Input } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { marked } from 'marked';
import { Message } from '../../../../core/models/message';

@Component({
  selector: 'app-chat-message',
  templateUrl: './chat-message.component.html',
  styleUrls: ['./chat-message.component.css'],
})
export class ChatMessageComponent {
  @Input() message: Message = { text: '', sender: '', is_interrupted: false };
  private markedMessage: string = '';

  async ngOnChanges() {
    const parsed = await marked(this.message.text || '');
    this.markedMessage = parsed;
  }

  get sanitizedMessage(): SafeHtml { 
    return this.sanitizer.bypassSecurityTrustHtml(this.markedMessage);
  }

  constructor(private sanitizer: DomSanitizer) {}
}
<div [class]="'chat-message ' + (message.sender === 'user' ? 'user' : 'bot')">
    <div class="message-content" [style.backgroundColor]="message.is_interrupted ? 'yellow' : ''">
      <div [innerHTML]="sanitizedMessage"></div>
      <!-- <span>{{ message.text }}</span> -->
    </div>
</div>

// chatbot_ui-legacy-React/src/components/ChatMessage.js
import React from 'react';
import '../style/ChatMessage.css';
import { marked } from 'marked';


function ChatMessage({ message, sender, is_interrupted }) {
    const className = sender === 'user' ? 'chat-message user' : 'chat-message bot';
    
    return (
        <div className={className}>
            <div className="message-content" style={{ backgroundColor: is_interrupted ? 'yellow' : '' }}>
                <div dangerouslySetInnerHTML={{ __html: marked(message) }} />
            </div>
        </div>
    );
}

export default ChatMessage;
